Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.name = "mysql"
  end
  
  config.vm.define "mysqlserver" do |mysqlserver|
      mysqlserver.vm.network "private_network", ip: "10.80.4.10"
      mysqlserver.vm.name = "mysqlserver"
  end

  #config.vm.provision "shell", inline: <<-SHELL
  #  apt-get update
  #  apt-get install -y mysql-server
  #SHELL
end
